modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="cmod"
version="0.0.1"
displayName="cmod"
credits="SUBSCRIBE TO CENJI"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="cenji"
description='''
Mod created by Cenji
'''

[[dependencies.cmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




